CREATE TABLE "tasks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"company_id" uuid NOT NULL,
	"title" varchar(500) NOT NULL,
	"description" text,
	"tag" varchar(50) NOT NULL,
	"task_type" varchar(50),
	"status" varchar(50) DEFAULT 'todo',
	"priority" integer DEFAULT 0,
	"complexity" integer,
	"queue_order" integer,
	"source" varchar(50) DEFAULT 'founder_requested',
	"suggestion_reasoning" text,
	"executability_type" varchar(50) DEFAULT 'can_run_now',
	"execution_mode" varchar(50),
	"assigned_to_agent_id" integer,
	"estimated_hours" numeric(4, 1),
	"estimated_credits" integer DEFAULT 1,
	"actual_credits_charged" integer DEFAULT 0,
	"verification_level" varchar(50),
	"refund_policy" varchar(50) DEFAULT 'manual_review',
	"failure_class" varchar(50),
	"related_task_ids" jsonb,
	"run_link" varchar(500),
	"markdown_link" varchar(500),
	"authorized_by" varchar(50),
	"authorization_reason" text,
	"max_turns" integer DEFAULT 200,
	"turn_count" integer DEFAULT 0,
	"started_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);