CREATE TABLE "companies" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"owner_id" uuid,
	"name" varchar(255) NOT NULL,
	"slug" varchar(100) NOT NULL,
	"one_liner" text,
	"original_idea" text,
	"claim_status" varchar(50) DEFAULT 'owned',
	"onboarding_status" varchar(50) DEFAULT 'initializing',
	"onboarding_journey" varchar(50),
	"plan_tier" varchar(50) DEFAULT 'free',
	"lifecycle" varchar(50) DEFAULT 'trial_active',
	"execution_state" varchar(50) DEFAULT 'active',
	"billing_state" varchar(50) DEFAULT 'free',
	"hosting_state" varchar(50) DEFAULT 'live',
	"company_stage" varchar(50) DEFAULT 'early',
	"subdomain" varchar(255),
	"email_identity" varchar(255),
	"github_repo" varchar(255),
	"render_service_id" varchar(255),
	"neon_database_id" varchar(255),
	"neon_connection_string" text,
	"custom_domain" varchar(255),
	"company_email" varchar(255),
	"timezone" varchar(50),
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"deleted_at" timestamp with time zone,
	CONSTRAINT "companies_slug_unique" UNIQUE("slug")
);