import type { CanaryScenario } from './canary-scenario-types';

export const CANARY_SCENARIOS: CanaryScenario[] = [
  {
    id: 'ai-course-marketplace',
    title: 'AI course marketplace',
    originalIdea: 'An AI-powered course marketplace where teachers upload lessons, students subscribe, AI summarizes lessons, and admins approve content.',
    capabilities: ['marketplace', 'auth', 'roles', 'uploads_storage', 'payments_stripe', 'ai_openai', 'admin_workflow', 'dashboard', 'crud', 'deployment_render'],
    requiredRoutes: [
      'app/api/health/route.ts',
      'app/api/canary-lessons/route.ts',
      'app/api/canary-lessons/[id]/approve/route.ts',
      'app/api/canary-ai-summary/route.ts',
      'app/api/canary-subscriptions/route.ts',
    ],
    requiredTables: ['canary_lessons', 'canary_subscriptions'],
    surfaceRequirements: [
      'Homepage / shows marketplace browse/search, teacher lesson creation/upload-ready flow, student subscription/payment-ready state, AI summary area, admin approval queue, and dashboard metrics.',
      'Use shadcn/ui and lucide-react; avoid generic AI-looking landing sections.',
    ],
    verificationRequirements: [
      'verify_user_journey covers lesson create, lesson list, AI summary, approval, and subscription.',
      'verify_db_state proves at least one canary_lessons row and one canary_subscriptions row.',
    ],
    liveChecks: [
      { name: 'GET /', path: '/' },
      { name: 'GET /api/health', path: '/api/health' },
      { name: 'POST /api/canary-lessons', path: '/api/canary-lessons', method: 'POST', body: {
        teacher_email: 'teacher@example.com',
        title: 'AI Product Strategy 101',
        category: 'Product',
        lesson_text: 'This lesson explains how product teams use customer signals, experiments, and dashboards to decide what to build next.',
        asset_name: 'strategy-lesson.pdf',
        asset_url: 'https://example.com/strategy-lesson.pdf',
        price_cents: 1900,
      }, capture: { key: 'lessonId', from: ['lesson.id', 'id'] } },
      { name: 'GET /api/canary-lessons', path: '/api/canary-lessons' },
      { name: 'POST /api/canary-ai-summary', path: '/api/canary-ai-summary', method: 'POST', body: {
        lesson_text: 'Teachers upload lessons, students subscribe, and admins approve course content before it appears in the marketplace.',
      } },
      { name: 'POST /api/canary-lessons/:id/approve', path: (state) => `/api/canary-lessons/${encodeURIComponent(String(state.lessonId ?? 'missing'))}/approve`, method: 'POST', body: { review_note: 'Canary approval' } },
      { name: 'POST /api/canary-subscriptions', path: '/api/canary-subscriptions', method: 'POST', body: (state) => ({
        student_email: 'student@example.com',
        lesson_id: state.lessonId,
        plan: 'monthly',
      }) },
    ],
    browserUiChecks: [{
      name: 'course marketplace browser surface',
      requiredTextPatterns: ['marketplace|courses?|lessons?', 'teacher|instructor', 'student|subscriber', 'admin|approval', 'summary|AI'],
      requiredButtonPatterns: ['create|add|upload|submit', 'approve', 'subscribe|checkout|payment'],
      requireNoConsoleErrors: true,
      journeys: [{
        name: 'signup reaches product-specific marketplace dashboard',
        startPath: '/sign-up',
        formFields: {
          name: 'Canary Student',
          email: 'ui-course-<timestamp>@example.com',
          password: 'CanaryPass123!',
        },
        submitPattern: 'create account|sign up|register',
        expectTextPatterns: ['marketplace|courses?|lessons?', 'teacher|instructor|student|subscriber|admin|approval|subscription'],
        rejectTextPatterns: ['authenticated app shell', 'Specialist agents', 'Your database', 'AI is pre-wired', 'db/schema\\.ts', 'Neon Postgres', 'official SDK'],
      }],
    }],
  },
  {
    id: 'vendor-compliance-portal',
    title: 'Vendor compliance portal',
    originalIdea: 'A vendor compliance portal where vendors onboard, upload documents, admins approve vendors, notifications are recorded, and teams monitor a dashboard.',
    capabilities: ['crud', 'uploads_storage', 'admin_workflow', 'email_notifications', 'dashboard', 'roles', 'auth', 'deployment_render'],
    requiredRoutes: [
      'app/api/health/route.ts',
      'app/api/canary-vendors/route.ts',
      'app/api/canary-vendor-documents/route.ts',
      'app/api/canary-vendors/[id]/approve/route.ts',
      'app/api/canary-notifications/route.ts',
    ],
    requiredTables: ['canary_vendors', 'canary_vendor_documents', 'canary_notifications'],
    surfaceRequirements: [
      'Homepage / shows vendor onboarding form, document upload-ready panel, admin approval table, notification status, and dashboard metrics.',
      'Admin approval rows show status, document count, reviewer note, and updated timestamp.',
      'Auth pages allow a vendor/admin user to create an account and reach the authenticated dashboard.',
    ],
    verificationRequirements: [
      'verify_user_journey covers vendor create, document record, approval, and notification-ready write.',
      'verify_db_state proves vendor and approval/notification rows landed.',
      'Browser UI proof signs up a unique user and reaches the authenticated dashboard/sign-out surface.',
    ],
    liveChecks: [
      { name: 'GET /', path: '/' },
      { name: 'GET /api/health', path: '/api/health' },
      { name: 'POST /api/canary-vendors', path: '/api/canary-vendors', method: 'POST', body: {
        vendor_email: 'vendor@example.com',
        company_name: 'Acme Supplies',
        category: 'Logistics',
        risk_level: 'medium',
      }, required: true, capture: { key: 'vendorId', from: ['vendor.id', 'id'] } },
      { name: 'POST /api/canary-vendor-documents', path: '/api/canary-vendor-documents', method: 'POST', body: (state) => ({
        vendor_id: state.vendorId,
        document_name: 'insurance.pdf',
        document_url: 'https://example.com/insurance.pdf',
        document_type: 'insurance',
      }), required: true },
      { name: 'POST /api/canary-vendors/:id/approve', path: (state) => `/api/canary-vendors/${encodeURIComponent(String(state.vendorId ?? 'missing'))}/approve`, method: 'POST', body: { review_note: 'Approved for canary' }, required: true },
      { name: 'GET /api/canary-notifications', path: '/api/canary-notifications' },
    ],
    browserUiChecks: [{
      name: 'vendor compliance browser surface',
      requiredTextPatterns: ['vendor', 'document', 'admin|approval', 'notification|activity', 'dashboard'],
      requiredButtonPatterns: ['register|create|submit', 'approve', 'reject', 'record|upload|save.*document|document.*(record|upload|save)'],
      requireNoConsoleErrors: true,
      journeys: [{
        name: 'vendor onboarding form submits through UI',
        formFields: {
          vendor_email: 'ui-vendor@example.com',
          company_name: 'UI Vendor Supplies',
          category: 'Logistics',
          risk_level: 'medium',
        },
        submitPattern: 'register|create|submit|onboard',
        expectTextPatterns: ['UI Vendor Supplies|ui-vendor@example.com|vendor', 'pending|submitted|created|dashboard|activity'],
      }, {
        name: 'document form submits through UI and renders saved document',
        formFields: {
          lp_vendor_id: '<vendorId>',
          lp_doc_name: 'browser-doc-<timestamp>.pdf',
          lp_doc_url: 'https://example.com/browser-doc.pdf',
          lp_doc_type: 'insurance',
        },
        submitPattern: 'save document|record|upload|save',
        expectTextPatterns: ['browser-doc|document', 'insurance|uploaded|saved|recorded'],
      }, {
        name: 'auth signup signout and signin surface works',
        startPath: '/sign-up',
        formFields: {
          name: 'Canary Auth User',
          email: 'canary-auth-<timestamp>@example.com',
          password: 'Password123!',
        },
        submitPattern: 'create account|sign up|register',
        expectTextPatterns: ['Compliance Dashboard|Dashboard', 'Sign out'],
        postSubmitActions: [{
          name: 'sign out clears authenticated dashboard',
          type: 'click',
          labelPattern: 'sign out|logout',
          expectTextPatterns: ['sign in|email|password|create account'],
          rejectTextPatterns: ['Compliance Dashboard|Vendor pipeline|Admin review queue'],
        }, {
          name: 'protected app denied after signout',
          type: 'goto',
          path: '/app',
          expectTextPatterns: ['sign in|email|password|create account'],
          rejectTextPatterns: ['Compliance Dashboard|Vendor pipeline|Admin review queue'],
        }],
      }],
    }],
    interactionChecks: [{
      name: 'register vendor button writes and renders vendor',
      labelPattern: 'register|create|submit|onboard',
      fields: {
        vendor_email: 'ui-vendor-<timestamp>@example.com',
        company_name: 'UI Vendor Supplies <timestamp>',
        category: 'Logistics',
        risk_level: 'medium',
      },
      api: 'POST /api/canary-vendors',
      dbTables: ['canary_vendors', 'canary_notifications'],
      expectTextPatterns: ['UI Vendor Supplies|ui-vendor', 'pending|submitted|created|dashboard|activity'],
    }, {
      name: 'save document button writes and renders document',
      labelPattern: 'save document|record|upload|save',
      fields: {
        lp_vendor_id: '<vendorId>',
        lp_doc_name: 'browser-doc-<timestamp>.pdf',
        lp_doc_url: 'https://example.com/browser-doc.pdf',
        lp_doc_type: 'insurance',
      },
      api: 'POST /api/canary-vendor-documents',
      dbTables: ['canary_vendor_documents'],
      expectTextPatterns: ['browser-doc|document', 'insurance|uploaded|saved|recorded'],
    }],
  },
  {
    id: 'booking-scheduling-app',
    title: 'Booking scheduling app',
    originalIdea: 'A booking app with availability slots, booking creation, duplicate-book prevention, and separate customer/admin views.',
    capabilities: ['booking', 'crud', 'dashboard', 'roles', 'auth', 'email_notifications', 'deployment_render'],
    requiredRoutes: ['app/api/health/route.ts', 'app/api/canary-availability/route.ts', 'app/api/canary-bookings/route.ts'],
    requiredTables: ['canary_availability_slots', 'canary_bookings'],
    surfaceRequirements: [
      'Homepage / shows slot picker/calendar-like availability, customer booking flow, admin booking queue, and status badges.',
      'Double-book prevention is implemented server-side, not only in UI.',
    ],
    verificationRequirements: [
      'verify_user_journey creates one slot, creates one booking, rejects second booking for same slot.',
      'verify_db_state proves one booking exists and no duplicate booking exists for that slot.',
    ],
    liveChecks: [
      { name: 'GET /', path: '/' },
      { name: 'GET /api/health', path: '/api/health' },
      { name: 'POST /api/canary-availability', path: '/api/canary-availability', method: 'POST', body: {
        provider_email: 'coach@example.com',
        starts_at: '2030-01-02T10:00:00.000Z',
        ends_at: '2030-01-02T10:30:00.000Z',
        timezone: 'UTC',
      }, capture: { key: 'slotId', from: ['slot.id', 'availability.id', 'id'] } },
      { name: 'POST /api/canary-bookings first', path: '/api/canary-bookings', method: 'POST', body: (state) => ({
        slot_id: state.slotId,
        customer_email: 'customer@example.com',
        note: 'First booking',
      }), capture: { key: 'bookingId', from: ['booking.id', 'id'] } },
      { name: 'POST /api/canary-bookings duplicate rejected', path: '/api/canary-bookings', method: 'POST', expectOk: false, body: (state) => ({
        slot_id: state.slotId,
        customer_email: 'second@example.com',
        note: 'Duplicate booking should fail',
      }) },
      { name: 'GET /api/canary-bookings', path: '/api/canary-bookings' },
    ],
    browserUiChecks: [{
      name: 'booking browser surface',
      requiredTextPatterns: ['availability|slots?|calendar', 'booking|reservation', 'customer', 'admin'],
      requiredButtonPatterns: ['create|add|save', 'book|reserve|schedule'],
      requireNoConsoleErrors: true,
    }],
  },
  {
    id: 'saas-billing-dashboard',
    title: 'SaaS billing dashboard',
    originalIdea: 'A SaaS billing dashboard with account/pricing UI, checkout or payment-ready flow, and persisted billing status.',
    capabilities: ['auth', 'roles', 'payments_stripe', 'dashboard', 'crud', 'analytics', 'deployment_render'],
    requiredRoutes: ['app/api/health/route.ts', 'app/api/canary-billing-accounts/route.ts', 'app/api/canary-checkout/route.ts', 'app/api/canary-billing-status/route.ts'],
    requiredTables: ['canary_billing_accounts', 'canary_billing_events'],
    surfaceRequirements: [
      'Homepage / shows account state, pricing/account controls, billing status card, checkout/payment link action, and dashboard metrics.',
      'If Stripe credentials are absent, persist payment_ready=true with explicit fallback status.',
    ],
    verificationRequirements: [
      'verify_user_journey covers account create, checkout/payment-ready action, and billing status retrieval.',
      'verify_db_state proves account and billing event/status rows landed.',
    ],
    liveChecks: [
      { name: 'GET /', path: '/' },
      { name: 'GET /api/health', path: '/api/health' },
      { name: 'POST /api/canary-billing-accounts', path: '/api/canary-billing-accounts', method: 'POST', body: {
        account_email: 'billing@example.com',
        company_name: 'Billing Canary Inc',
        plan: 'pro',
      }, capture: { key: 'accountId', from: ['account.id', 'id'] } },
      { name: 'POST /api/canary-checkout', path: '/api/canary-checkout', method: 'POST', body: (state) => ({
        account_id: state.accountId,
        plan: 'pro',
        seats: 5,
      }) },
      { name: 'GET /api/canary-billing-status', path: '/api/canary-billing-status' },
    ],
    browserUiChecks: [{
      name: 'billing browser surface',
      requiredTextPatterns: ['billing|subscription', 'pricing|plan', 'account', 'status'],
      requiredButtonPatterns: ['checkout|payment|subscribe|upgrade', 'create|save|start'],
      requireNoConsoleErrors: true,
    }],
  },
  {
    id: 'ai-document-analyzer',
    title: 'AI document analyzer',
    originalIdea: 'An AI document analyzer where users submit documents, AI extracts a summary, results are stored, and searchable history/RAG-search works.',
    capabilities: ['uploads_storage', 'ai_openai', 'rag_search', 'search', 'crud', 'dashboard', 'auth', 'deployment_render'],
    requiredRoutes: ['app/api/health/route.ts', 'app/api/canary-documents/route.ts', 'app/api/canary-analyze/route.ts', 'app/api/canary-document-search/route.ts'],
    requiredTables: ['canary_documents', 'canary_document_analyses'],
    surfaceRequirements: [
      'Homepage / shows document input/upload-ready flow, AI extraction result panel, stored history, and search/RAG results.',
      'Use fixed Gemini 2 Flash runtime AI; /api/canary-analyze must not return fallback=true when AI gateway credentials are configured.',
    ],
    verificationRequirements: [
      'verify_user_journey covers document create, analysis, stored result, and search/history query.',
      'verify_db_state proves document and analysis rows landed.',
    ],
    liveChecks: [
      { name: 'GET /', path: '/' },
      { name: 'GET /api/health', path: '/api/health' },
      { name: 'POST /api/canary-documents', path: '/api/canary-documents', method: 'POST', required: true, body: {
        title: 'Vendor Agreement',
        document_text: 'This vendor agreement requires annual compliance review, insurance certificates, and data protection controls.',
        source_name: 'vendor-agreement.txt',
      }, capture: { key: 'documentId', from: ['document.id', 'id'] } },
      { name: 'POST /api/canary-analyze', path: '/api/canary-analyze', method: 'POST', required: true, body: (state) => ({
        document_id: state.documentId,
        document_text: 'This vendor agreement requires annual compliance review, insurance certificates, and data protection controls.',
      }), rejectTruthyJsonPaths: ['analysis.fallback', 'fallback'], rejectResponseTextPatterns: ['AI FALLBACK', 'Analysis failed'] },
      { name: 'POST /api/canary-document-search', path: '/api/canary-document-search', method: 'POST', required: true, body: { query: 'insurance compliance controls' } },
    ],
    browserUiChecks: [{
      name: 'AI document analyzer browser surface',
      requiredTextPatterns: ['document', 'analy[sz]e|extract|summary', 'history|stored', 'search|RAG'],
      requiredButtonPatterns: ['upload|submit|add|save|analy[sz]e document', 'analy[sz]e|extract|summarize', 'search'],
      requireNoConsoleErrors: true,
      journeys: [{
        name: 'document analyzer form submits through UI',
        formFields: {
          title: 'UI Vendor Agreement',
          source_file: 'ui-vendor-agreement.txt',
          document_text: 'This UI vendor agreement requires annual insurance review and data protection controls.',
        },
        submitPattern: 'upload|submit|add|save|analy[sz]e document',
        expectTextPatterns: ['summary|key points|analysis', 'insurance|controls|vendor'],
      }],
    }],
  },
  {
    id: 'adversarial-booking-marketplace',
    title: 'Adversarial AI booking marketplace',
    originalIdea: 'A weird mixed app: AI-powered booking marketplace with vendor onboarding, subscriptions, uploads, admin approval, and analytics dashboard.',
    capabilities: ['marketplace', 'booking', 'auth', 'roles', 'payments_stripe', 'uploads_storage', 'ai_openai', 'admin_workflow', 'analytics', 'dashboard', 'crud', 'deployment_render'],
    requiredRoutes: [
      'app/api/canary-vendors/route.ts',
      'app/api/canary-marketplace-listings/route.ts',
      'app/api/canary-availability/route.ts',
      'app/api/canary-bookings/route.ts',
      'app/api/canary-subscriptions/route.ts',
      'app/api/canary-analytics/route.ts',
    ],
    requiredTables: ['canary_vendors', 'canary_marketplace_listings', 'canary_availability_slots', 'canary_bookings', 'canary_subscriptions', 'canary_analytics_events'],
    surfaceRequirements: [
      'Homepage / combines vendor onboarding, listing marketplace, booking slot picker, subscription/payment-ready action, admin approval, AI help/summary, and analytics dashboard.',
      'Build by vertical slices; do not collapse into a single generic CRUD table.',
    ],
    verificationRequirements: [
      'verify_user_journey covers at least three slices: vendor approval, booking, subscription/payment-ready, and analytics.',
      'verify_db_state proves writes across at least three domain tables.',
    ],
    liveChecks: [
      { name: 'GET /', path: '/' },
      { name: 'POST /api/canary-vendors', path: '/api/canary-vendors', method: 'POST', body: { vendor_email: 'vendor@example.com', company_name: 'Mixed Canary Vendor' }, capture: { key: 'vendorId', from: ['vendor.id', 'id'] } },
      { name: 'POST /api/canary-marketplace-listings', path: '/api/canary-marketplace-listings', method: 'POST', body: (state) => ({ vendor_id: state.vendorId, title: 'AI Strategy Session', price_cents: 9900 }), capture: { key: 'listingId', from: ['listing.id', 'id'] } },
      { name: 'POST /api/canary-availability', path: '/api/canary-availability', method: 'POST', body: (state) => ({ listing_id: state.listingId, starts_at: '2030-01-03T12:00:00.000Z', ends_at: '2030-01-03T13:00:00.000Z' }), capture: { key: 'slotId', from: ['slot.id', 'availability.id', 'id'] } },
      { name: 'POST /api/canary-bookings', path: '/api/canary-bookings', method: 'POST', body: (state) => ({ slot_id: state.slotId, customer_email: 'customer@example.com' }) },
      { name: 'POST /api/canary-subscriptions', path: '/api/canary-subscriptions', method: 'POST', body: (state) => ({ listing_id: state.listingId, student_email: 'student@example.com', plan: 'monthly' }) },
      { name: 'GET /api/canary-analytics', path: '/api/canary-analytics' },
    ],
    browserUiChecks: [{
      name: 'adversarial mixed app browser surface',
      requiredTextPatterns: ['marketplace|listing', 'booking|availability', 'vendor', 'analytics|dashboard', 'approval|admin'],
      requiredButtonPatterns: ['approve', 'book|reserve|schedule', 'subscribe|checkout|payment', 'create|add|save'],
      requireNoConsoleErrors: true,
    }],
  },
  {
    id: 'existing-app-extension',
    title: 'Existing app extension',
    originalIdea: 'An existing deployed app that needs billing, RAG document search, and an admin dashboard added without replacing the existing product.',
    capabilities: ['payments_stripe', 'rag_search', 'uploads_storage', 'admin_workflow', 'dashboard', 'crud', 'auth', 'deployment_render'],
    requiredRoutes: ['app/api/health/route.ts', 'app/api/canary-existing-health/route.ts', 'app/api/canary-documents/route.ts', 'app/api/canary-document-search/route.ts', 'app/api/canary-billing-status/route.ts'],
    requiredTables: ['canary_documents', 'canary_document_analyses', 'canary_billing_accounts'],
    surfaceRequirements: [
      'Before planning, call read_codebase_map plus build_code_graph/query_code_graph and extend the existing app. Do not create a duplicate generic app.',
      'Homepage keeps a visible existing-app signal and adds billing, RAG document search/history, and admin dashboard sections.',
    ],
    verificationRequirements: [
      'verify_user_journey proves existing health route still works plus new billing and RAG search routes work.',
      'verify_db_state proves document/search or billing rows landed.',
    ],
    extraCriticalTools: ['read_codebase_map', 'build_code_graph', 'query_code_graph'],
    requiresExistingBaseline: true,
    baselineTaskDescription: 'Build and deploy a minimal existing customer notes app with /api/canary-existing-health before running the extension task.',
    liveChecks: [
      { name: 'GET /', path: '/' },
      { name: 'GET /api/health', path: '/api/health' },
      { name: 'GET /api/canary-existing-health', path: '/api/canary-existing-health' },
      { name: 'POST /api/canary-documents', path: '/api/canary-documents', method: 'POST', body: { title: 'Existing App Policy', document_text: 'The existing app needs billing and searchable admin documents.' }, capture: { key: 'documentId', from: ['document.id', 'id'] } },
      { name: 'POST /api/canary-document-search', path: '/api/canary-document-search', method: 'POST', body: { query: 'billing documents' } },
      { name: 'GET /api/canary-billing-status', path: '/api/canary-billing-status' },
    ],
    browserUiChecks: [{
      name: 'existing app extension browser surface',
      requiredTextPatterns: ['existing|notes|customer', 'billing|subscription', 'document|RAG|search', 'admin|dashboard'],
      requiredButtonPatterns: ['search', 'checkout|billing|payment|subscribe', 'create|add|save|upload'],
      requireNoConsoleErrors: true,
    }],
  },
];

export const CORE_CANARY_SCENARIO_IDS = CANARY_SCENARIOS.map((scenario) => scenario.id);
