// Custom Cloudflare Worker entry — wraps OpenNext-generated worker.
//
// PROBLEM
// `@opennextjs/cloudflare` outputs `.open-next/worker.js` with only `fetch`.
// Cron Triggers in `wrangler.toml` need a `scheduled()` export, otherwise the
// crons register on the platform but never invoke any code (silent inert).
//
// FIX
// This entry re-exports the OpenNext fetch handler + Durable Object classes
// (so we don't break the Next.js app or asset/cache plumbing) and ADDS a
// `scheduled()` handler that maps each cron expression to the matching
// `/api/cron/*` route via internal fetch. Internal fetch is preferred over
// calling the route handler directly because:
//   1. The OpenNext worker bootstraps `runWithCloudflareRequestContext` and
//      module-loads the Next server (handler.mjs is dynamic-imported); calling
//      that context per-cron via fetch keeps env/binding wiring identical to
//      the live HTTP path.
//   2. There is no public network hop — `worker.fetch(req, env, ctx)` is a
//      direct in-process call, not an outbound request.
//
// Auth: each cron route checks `x-cron-secret: env.CRON_SECRET`. We forward
// the same secret here. If `CRON_SECRET` is unset on the deployed Worker the
// routes 503 ("Cron not configured") — not silent failure.
//
// To wire this up, `wrangler.toml` `main` is repointed at this file. Wrangler
// bundles TS directly, so no separate build step is needed.

// @ts-expect-error — OpenNext output is generated by `opennextjs-cloudflare build`
import openNextWorker from "../.open-next/worker.js";

// Re-export Durable Object classes that the OpenNext worker exports. Wrangler
// requires these to be exported from the *entry* module — re-exporting from
// the imported worker.js doesn't satisfy the runtime binding lookup.
// @ts-expect-error — generated by OpenNext at build time
export { DOQueueHandler } from "../.open-next/.build/durable-objects/queue.js";
// @ts-expect-error — generated by OpenNext at build time
export { DOShardedTagCache } from "../.open-next/.build/durable-objects/sharded-tag-cache.js";
// @ts-expect-error — generated by OpenNext at build time
export { BucketCachePurge } from "../.open-next/.build/durable-objects/bucket-cache-purge.js";

// ─────────────────────────────────────────────────────────────────
// Cron → route mapping. KEEP IN SYNC with [triggers.crons] in wrangler.toml.
// CF passes `event.cron` as the literal cron expression string we registered.
// Method matters: each route handler exports either GET, POST, or both.
// ─────────────────────────────────────────────────────────────────
type CronRoute = { path: string; method: "GET" | "POST"; name: string };

const CRON_DISPATCH: Record<string, CronRoute> = {
  "0 2 * * *":   { path: "/api/cron/night-shift",        method: "POST", name: "night-shift" },
  "0 */6 * * *": { path: "/api/cron/recurring",          method: "POST", name: "recurring" },
  "0 3 * * *":   { path: "/api/cron/trial-expiry",       method: "GET",  name: "trial-expiry" },
  "*/15 * * * *":{ path: "/api/cron/platform-ops",       method: "GET",  name: "platform-ops" },
  "0 4 * * *":   { path: "/api/cron/credit-renewal",     method: "POST", name: "credit-renewal" },
  "*/5 * * * *": { path: "/api/cron/onboarding-cleanup", method: "POST", name: "onboarding-cleanup" },
  "* * * * *":   { path: "/api/cron/queue-tick",         method: "POST", name: "queue-tick" },
  "*/3 * * * *": { path: "/api/cron/lease-reclaim",      method: "POST", name: "lease-reclaim" },
  "5 * * * *":   { path: "/api/cron/platform-ops-triage", method: "POST", name: "platform-ops-triage" },
  "20 * * * *":  { path: "/api/cron/platform-ops-fix",    method: "POST", name: "platform-ops-fix" },
};

interface CronEnv {
  CRON_SECRET?: string;
  // OpenNext + DO + R2 + Workflows + LLM bindings live here too; we only use
  // CRON_SECRET directly. Everything else is read by the route handlers via
  // process.env / Cloudflare context, which OpenNext already wires.
  [key: string]: unknown;
}

interface ScheduledLikeEvent {
  cron: string;
  scheduledTime: number;
}

// Structural shape of CF's `ExecutionContext`. Avoids pulling
// `@cloudflare/workers-types` as a dep just for one type. Wrangler
// types-check this file separately at deploy time.
interface CfExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
  props?: unknown;
}

export default {
  // Pass-through fetch — no behavior change for the live Next.js app.
  fetch: openNextWorker.fetch,

  // Cron dispatcher.
  async scheduled(
    event: ScheduledLikeEvent,
    env: CronEnv,
    ctx: CfExecutionContext,
  ): Promise<void> {
    const route = CRON_DISPATCH[event.cron];
    if (!route) {
      // Unknown cron expression — log and bail. Don't throw: CF retries
      // throwing scheduled handlers, which would compound the problem.
      console.warn(
        `[cf-worker-entry] No handler for cron "${event.cron}" at ${new Date(event.scheduledTime).toISOString()}`,
      );
      return;
    }

    const secret = env.CRON_SECRET;
    if (!secret) {
      console.error(
        `[cf-worker-entry] CRON_SECRET unset; ${route.name} cron at ${new Date(event.scheduledTime).toISOString()} skipped`,
      );
      return;
    }

    // Internal-fetch URL: hostname is irrelevant (never leaves the worker),
    // but Next/middleware/OpenNext expect a parseable absolute URL. Using
    // baljia.ai keeps any host-based middleware (subdomain routing in
    // src/middleware.ts) on the platform path rather than founder-app path.
    const url = `https://baljia.ai${route.path}`;
    const req = new Request(url, {
      method: route.method,
      headers: {
        "x-cron-secret": secret,
        "content-type": "application/json",
        "user-agent": "cf-worker-cron-dispatcher",
      },
    });

    const start = Date.now();
    try {
      // ctx.waitUntil keeps the worker alive past return so async work in the
      // route handler completes. We also await here so logs reflect status.
      const respPromise: Promise<Response> = openNextWorker.fetch(req, env, ctx);
      ctx.waitUntil(respPromise);
      const resp = await respPromise;
      const elapsed = Date.now() - start;
      if (!resp.ok) {
        const bodyPreview = await resp.text().then((t: string) => t.slice(0, 500)).catch(() => "<no body>");
        console.error(
          `[cf-worker-entry] cron ${route.name} -> ${resp.status} in ${elapsed}ms: ${bodyPreview}`,
        );
      } else {
        console.log(`[cf-worker-entry] cron ${route.name} -> ${resp.status} in ${elapsed}ms`);
      }
    } catch (err) {
      const elapsed = Date.now() - start;
      const msg = err instanceof Error ? `${err.message}\n${err.stack ?? ""}` : String(err);
      console.error(`[cf-worker-entry] cron ${route.name} threw after ${elapsed}ms: ${msg}`);
      // Swallow — see comment above on retry semantics.
    }
  },
};
